services:
  php:
    image: 'ghcr.io/koza4ok/php-helloworld:latest'
    stop_grace_period: 20s
    networks:
      - overlay
    deploy:
      replicas: 2
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      labels:
        - traefik.enable=true
        - traefik.http.routers.secubi-php.rule=Host(`your-domain.com`)
        - traefik.http.services.secubi-php.loadbalancer.server.port=80
    healthcheck:
      test: ["CMD", "php", "-v"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s # Gives PHP time to boot before checking
